Hotfix/2.14.1
int-brain-lab/ibllib pull request #511
Opened 2022-09-16 11:15 UTC by oliche

2022-09-16 15:07 UTC, k1o0 requested changes

2022-09-16 15:07 UTC, k1o0 commented on ibllib/__init__.py
> +__version__ = "2.14.1   "
@oliche @juhuntenburg This extra whitespace might be causing problems....

2022-09-16 16:45 UTC, oliche commented
Thanks Miles.

The current version of the CI matches the develop branch of ibllib and I did attempt creating a hotfix/2.14.1 branch on iblscripts to see if the CI runs.

In the worst case we'll release from ibllib/develop on Monday !

2022-09-20 07:11 UTC, oliche commented
In release 2.15

2022-09-20 07:11 UTC, closed without merging