add @sleepless decorator
int-brain-lab/ibllib pull request #655
Opened 2023-10-05 09:47 UTC by bimac

2023-10-10 10:00 UTC, oliche commented on ibllib/pipes/misc.py
> +def sleepless(func: Callable[..., Any]) -> Callable[..., Any]:
Is there anyway to test the function (at least the syntax and arguments ? )
Even on linux you can probably decorate a dummy function and run it just to see that it returns the proper number of arguments and that the syntax is correct. You will at least get coverage from this.

2023-10-10 10:02 UTC, oliche requested changes
Maybe just add a simple test (even in Linux) that decorates a dummy sum function.
This is just to get coverage so if some arguments are refactored we get notified !

2023-11-13 16:55 UTC, bimac commented
Added a basic test ...

2023-12-15 11:16 UTC, k1o0 approved these changes

2023-12-15 11:17 UTC, merged